/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.userinterface.vaccination;

import edu.neu.csye6200.University;
import edu.neu.csye6200.classRoom.ClassRoom;
import edu.neu.csye6200.health.VaccineRecord;
import javax.swing.JPanel;

/**
 *
 * @author manojreddy
 */
public class UpdateVaccinationRecordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateVaccinationRecordJPanel
     */
    private JPanel containerjPanel;
    private University university;
    private VaccineRecord vaccineRecord;
    
    public UpdateVaccinationRecordJPanel(JPanel containerjPanel, University university, VaccineRecord vaccineRecord) {
        initComponents();
        this.containerjPanel = containerjPanel;
        this.university = university;
        this.vaccineRecord = vaccineRecord;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
