/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.userinterface.classroomGroup;

import edu.neu.csye6200.Person;
import edu.neu.csye6200.University;
import edu.neu.csye6200.classRoomGroup.ClassRoomGroup;
import edu.neu.csye6200.classRoomGroup.ClassRoomGroup.AgeGroup;
import edu.neu.csye6200.student.Student;
import edu.neu.csye6200.teacher.Teacher;
import edu.neu.csye6200.userinterface.student.StudentMangementHomeJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;

/**
 *
 * @author manojreddy
 */
public class CreateNewClassRoomGroupJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewClassRoomGroupJPanel
     */
    
    private JPanel containerjPanel;
    private University university;
    
    public CreateNewClassRoomGroupJPanel(JPanel containerjPanel, University university) {
        initComponents();
        this.containerjPanel = containerjPanel;
        this.university = university;
        
        populateData();
    }

    private void populateData() {
        
        teacherjComboBox.removeAllItems();
        university.getTeacherController().getUnassignedTeacher().stream().map(person -> (Teacher) person).forEachOrdered(teacher -> {
            teacherjComboBox.addItem(String.valueOf(teacher.getTId()) + "-" + teacher.getName());
        });
                
        ageGroupjComboBox.removeAllItems();
        for( AgeGroup value : ClassRoomGroup.AgeGroup.values()){
            ageGroupjComboBox.addItem(value.getDisplayValue());
        }
        ageGroupjComboBox.setSelectedIndex(AgeGroup.SIX_TWELVE.getValue());
        
        
        studentsjList.removeAll();
        List<Person> studentList = university.getStudentController().getUnAssignedStudentListBasedOnAgeGroup(AgeGroup.SIX_TWELVE);
        String[] inputData = new String[studentList.size()];
        int i=0;
        for(Person person:studentList) {
            inputData[i]= ((Integer)((Student)person).getSId()).toString()+"-"+person.getName();
            i++;
        }
        studentsjList.setListData( inputData);
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        teacherjComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        savejButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsjList = new javax.swing.JList<>();
        ageGroupjComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Create New ClassRoom Group");

        jButton1.setText("< < Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Id :");

        idjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Teacher :");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Student :");

        savejButton.setText("Save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(studentsjList);

        ageGroupjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGroupjComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Age Group");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teacherjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageGroupjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(savejButton)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageGroupjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savejButton))
                    .addComponent(jLabel4))
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idjTextFieldActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        // TODO add your handling code here:
        
        int id = Integer.valueOf(idjTextField.getText());
        int[] selectedStudents = studentsjList.getSelectedIndices();
        
        List<Person> students = new ArrayList<>();
        for(int student:selectedStudents) {
            students.add((Student) university.getStudentController().getUnassignedStudent().get(student));
        }
        
        Teacher teacher  = (Teacher) university.getTeacherController().getUnassignedTeacher().get(teacherjComboBox.getSelectedIndex());
        
        System.out.println(students.size());
        
        university.getClassRoomGroupController()
                .addClassRoomGroup( id, teacher , students,AgeGroup.valueOf(ageGroupjComboBox.getSelectedIndex()));
        
        populateData();
    }//GEN-LAST:event_savejButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        containerjPanel.remove(this);
        
        Component[] components = containerjPanel.getComponents();
        ClassRoomGroupManagementHomeJPanel classRoomGroupManagementHomeJPanel = (ClassRoomGroupManagementHomeJPanel) components[components.length-1];
        classRoomGroupManagementHomeJPanel.populateClassRoomgroups();
        
        CardLayout cardLayout = (CardLayout) containerjPanel.getLayout();
        cardLayout.previous(containerjPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ageGroupjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGroupjComboBoxActionPerformed
        System.out.println("called");
        List<Person> studentList = university.getStudentController().getUnAssignedStudentListBasedOnAgeGroup(AgeGroup.valueOf(ageGroupjComboBox.getSelectedIndex()));
        String[] inputData = new String[studentList.size()];
        System.out.println("studentList size"+studentList.size());
        int i=0;
        for(Person person:studentList) {
            inputData[i]= ((Integer)((Student)person).getSId()).toString()+"-"+person.getName();
            i++;
        }
        studentsjList.setListData( inputData);
    }//GEN-LAST:event_ageGroupjComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ageGroupjComboBox;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton savejButton;
    private javax.swing.JList<String> studentsjList;
    private javax.swing.JComboBox<String> teacherjComboBox;
    // End of variables declaration//GEN-END:variables
}
