/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.userinterface.classroomGroup;

import edu.neu.csye6200.University;
import edu.neu.csye6200.classRoomGroup.ClassRoomGroup;
import javax.swing.JPanel;

/**
 *
 * @author manojreddy
 */
public class UpdateClassRoomGroupJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateClassRoomGroupJPanel
     */
    private JPanel containerjPanel;
    private University university;
    private ClassRoomGroup classRoomGroup;
    
    public UpdateClassRoomGroupJPanel(JPanel containerjPanel, University university, ClassRoomGroup classRoomGroup) {
        initComponents();
        this.containerjPanel = containerjPanel;
        this.university = university;
        this.classRoomGroup = classRoomGroup;
        
        populateData();
    }

    private void populateData() {
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
