/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.userinterface.classroomGroup;

import edu.neu.csye6200.Person;
import edu.neu.csye6200.University;
import edu.neu.csye6200.classRoomGroup.ClassRoomGroup;
import edu.neu.csye6200.classRoomGroup.ClassRoomGroupController;
import edu.neu.csye6200.student.Student;
import edu.neu.csye6200.teacher.Teacher;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author manojreddy
 */
public class UpdateClassRoomGroupJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateClassRoomGroupJPanel
     */
    private JPanel containerjPanel;
    private University university;
    private ClassRoomGroup classRoomGroup;
    
    public UpdateClassRoomGroupJPanel(JPanel containerjPanel, University university, ClassRoomGroup classRoomGroup) {
        initComponents();
        this.containerjPanel = containerjPanel;
        this.university = university;
        this.classRoomGroup = classRoomGroup;
        
        populateData();
    }

    private void populateData() {
        idjTextField.setText(((Integer)this.classRoomGroup.getId()).toString());
        
        teacherjComboBox.removeAllItems();
        teacherjComboBox.addItem(String.valueOf(((Teacher)this.classRoomGroup.getTeacher()).getTId()) + "-" + ((Teacher)this.classRoomGroup.getTeacher()).getName());
        for(Person person:university.getTeacherController().getUnassignedTeacher()) {
            
            Teacher teacher  = (Teacher) person;
            teacherjComboBox.addItem(String.valueOf(teacher.getTId()) + "-" + teacher.getName());
        }
        
        teacherjComboBox.setSelectedIndex(0);
        
        ageGroupjComboBox1.removeAllItems();
        for( ClassRoomGroup.AgeGroup value : ClassRoomGroup.AgeGroup.values()){
            ageGroupjComboBox1.addItem(value.getDisplayValue());
        }
        ageGroupjComboBox1.setSelectedIndex(this.classRoomGroup.getAgeGroup().getValue());
        
        studentsjList.removeAll();
        List<Person> studentList = university.getStudentController().getUnAssignedStudentListBasedOnAgeGroup(this.classRoomGroup.getAgeGroup());
        List<Person> currentStudents = this.classRoomGroup.getStudents();
        String[] inputData = new String[studentList.size()+currentStudents.size()];
        int i=0;
        int[] selectedIndices = new int[currentStudents.size()];
        for(Person person:currentStudents) {
            inputData[i]= ((Integer)((Student)person).getSId()).toString()+"-"+person.getName();
            selectedIndices[i]=i;
            i++;
        }
        for(Person person:studentList) {
            inputData[i]= ((Integer)((Student)person).getSId()).toString()+"-"+person.getName();
            i++;
        }
        
        studentsjList.setListData( inputData);
        studentsjList.setSelectedIndices(selectedIndices);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        teacherjComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        updatejButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsjList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ageGroupjComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        idjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Teacher :");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Student :");

        updatejButton.setText("update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(studentsjList);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Update ClassRoom Group");

        jButton1.setText("< < Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Id :");

        ageGroupjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGroupjComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Age Group");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teacherjComboBox, 0, 219, Short.MAX_VALUE)
                            .addComponent(ageGroupjComboBox1, 0, 219, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(updatejButton)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageGroupjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatejButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idjTextFieldActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        String id = idjTextField.getText();
        int idx = teacherjComboBox.getSelectedIndex();
        Person teacher = idx ==0? this.classRoomGroup.getTeacher():university.getTeacherController().getUnassignedTeacher().get(idx-1);
        List<Person> studentList = new ArrayList(this.classRoomGroup.getStudents());
        studentList.addAll( university.getStudentController().getUnassignedStudent());
        List<Person> selectedStudentList = new ArrayList();
        for(int index:studentsjList.getSelectedIndices())
        {
            selectedStudentList.add(studentList.get(index));
        }
        ClassRoomGroupController controller = university.getClassRoomGroupController();
        controller.modifyClassRoomGroup(classRoomGroup, Integer.parseInt(id), (Teacher)teacher, selectedStudentList,ClassRoomGroup.AgeGroup.valueOf(ageGroupjComboBox1.getSelectedIndex()+1));
        classRoomGroup = controller.getClassRoomGroupById(Integer.parseInt(id));
        JOptionPane.showMessageDialog(this, "Successfully updated Class Room Group record");
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*
         containerjPanel.remove(this);

        Component[] components = containerjPanel.getComponents();
        StudentMangementHomeJPanel studentMangementHomeJPanel = (StudentMangementHomeJPanel) components[components.length-1];
        studentMangementHomeJPanel.populateTable(university.getStudentController().getStudentList());

        CardLayout cardLayout = (CardLayout) containerjPanel.getLayout();
        cardLayout.previous(containerjPanel);
        */
        
        containerjPanel.remove(this);
        Component[] components = containerjPanel.getComponents();
        ClassRoomGroupManagementHomeJPanel groupManagementHomeJPanel = (ClassRoomGroupManagementHomeJPanel) components[components.length-1];
        groupManagementHomeJPanel.populateClassRoomgroups();
        CardLayout cardLayout = (CardLayout) containerjPanel.getLayout();
        cardLayout.previous(containerjPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ageGroupjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGroupjComboBox1ActionPerformed
        System.out.println("called");
        List<Person> studentList = university.getStudentController().getUnAssignedStudentListBasedOnAgeGroup(ClassRoomGroup.AgeGroup.valueOf(ageGroupjComboBox1.getSelectedIndex()));
        String[] inputData = new String[studentList.size()];
        int i=0;
        for(Person person:studentList) {
            inputData[i]= ((Integer)((Student)person).getSId()).toString()+"-"+person.getName();
            i++;
        }
        studentsjList.setListData( inputData);
    }//GEN-LAST:event_ageGroupjComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ageGroupjComboBox1;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> studentsjList;
    private javax.swing.JComboBox<String> teacherjComboBox;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
